"""Compare printout pagination between the HTML print preview and the PDF.

A printout (a worksheet, a handout, or a project-like block with workspace) is
paginated twice by completely separate machinery: in the browser by
`pretext-printouts.js`, which measures every row and runs a global optimiser
over the whole printout, and in LaTeX by TeX's own page builder.  The two are
supposed to land on the same page breaks.  This script measures whether they
do.

Method
------
Both sides are asked which page each *block* of a printout ended up on, keyed
by the block's PreTeXt id -- the same string appears as an HTML `id` attribute
and, when the LaTeX is built with `debug.printout.labels=yes`, as a LaTeX
label `ptxblock-<id>` whose page number lands in the `.aux` file.  Joining on
that id gives a per-block comparison; page numbers are all the comparison
needs, and a `\\label` is portable across every TeX engine.

PDF pages are absolute document pages, HTML pages are numbered from one within
the printout, so PDF numbers are made relative to the first page any block of
that printout appears on.  A printout always starts a fresh page (the
`\\newgeometry` that opens one includes a `\\clearpage`), so those agree by
construction.

Usage
-----
    python scripts/printout_parity.py --save-baseline
    ...make a change to the XSL...
    python scripts/printout_parity.py

The second run prints what moved relative to the baseline.  Run it from the
root of the pretext-testing repository, with the CLI's virtual environment
active so that `pretext` imports and the local core is the one under test.
"""

from __future__ import annotations

import argparse
import functools
import http.server
import json
import re
import shutil
import socketserver
import subprocess
import sys
import threading
from pathlib import Path
from typing import Any

# Targets to compare: a LaTeX target and the HTML target built from the same
# source and publication file.
DEFAULT_PAIRS = [("sa-tex", "sa-web"), ("sb-tex", "sb-web")]

BASELINE_NAME = "printout-parity-baseline.json"


# ---------------------------------------------------------------- building --


def build_target(
    project_root: Path, name: str, stringparams: dict[str, str], generate: bool = False
) -> Path:
    """Build one target with extra stringparams; return its output directory.

    Assets are not regenerated by default: they do not depend on anything this
    script varies, and generating them dominates the runtime of a comparison
    that is meant to be run after every change.
    """
    from pretext import project as pr

    project = pr.Project.parse(project_root)
    target = project.get_target(name)
    target.stringparams.update(stringparams)
    print(f"[parity] building {name} ...", flush=True)
    target.build(generate=generate)
    return target.output_dir_abspath()


def compile_pdf(tex_dir: Path) -> Path:
    """Run LaTeX over the built .tex file; return the .aux file.

    Two passes: the first writes the labels, the second lets anything that
    consumes them (page references, and the widths they set) settle, so the
    page numbers recorded are the ones a real build would show.
    """
    tex_files = sorted(tex_dir.glob("*.tex"))
    if not tex_files:
        raise SystemExit(f"no .tex file in {tex_dir}")
    # The main file is the one with \documentclass in it.
    main = None
    for candidate in tex_files:
        if "\\documentclass" in candidate.read_text(encoding="utf-8", errors="replace")[:4000]:
            main = candidate
            break
    if main is None:
        raise SystemExit(f"no file with \\documentclass in {tex_dir}")
    engine = shutil.which("pdflatex")
    if engine is None:
        raise SystemExit("pdflatex not found on PATH")
    for pass_number in (1, 2):
        print(f"[parity] pdflatex pass {pass_number} on {main.name} ...", flush=True)
        result = subprocess.run(
            [engine, "-interaction=nonstopmode", "-halt-on-error", main.name],
            cwd=tex_dir,
            capture_output=True,
            text=True,
            errors="replace",
        )
        if result.returncode != 0:
            tail = "\n".join(result.stdout.splitlines()[-40:])
            raise SystemExit(f"pdflatex failed:\n{tail}")
    return main.with_suffix(".aux")


# ----------------------------------------------------------------- parsing --


def _read_group(text: str, start: int) -> tuple[str, int]:
    """Read a brace-delimited group starting at `start` (which indexes a '{').

    Returns the contents and the index just past the closing brace.
    """
    assert text[start] == "{"
    depth = 0
    i = start
    while i < len(text):
        char = text[i]
        if char == "\\":
            i += 2
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
        i += 1
    raise ValueError("unbalanced braces in .aux file")


def parse_aux(aux_path: Path) -> dict[str, int]:
    """Map block id -> absolute PDF page, from the `ptxblock-` labels.

    An exercise that is reproduced in a solutions division is rendered from
    the *same* source node a second time, so it carries the same id and emits
    the probe twice -- once in the printout, once in the back matter.  The
    printout comes first in document order, and the `.aux` is written in
    document order, so the first occurrence is the one to keep.  (LaTeX keeps
    the last, which is why it warns about the duplicate; nothing here depends
    on what LaTeX resolves the label to.)
    """
    text = aux_path.read_text(encoding="utf-8", errors="replace")
    pages: dict[str, int] = {}
    for match in re.finditer(r"\\newlabel\{ptxblock-", text):
        name_start = match.end() - len("ptxblock-") - 1
        name, after_name = _read_group(text, name_start)
        block_id = name[len("ptxblock-") :]
        # A package may add derived labels (foo@cref and friends); skip them.
        if "@" in block_id:
            continue
        if after_name >= len(text) or text[after_name] != "{":
            continue
        body, _ = _read_group(text, after_name)
        # body is {ref}{page}{title}{anchor}{} -- the second group is the page
        fields = []
        i = 0
        while i < len(body) and len(fields) < 2:
            if body[i] == "{":
                field, i = _read_group(body, i)
                fields.append(field)
            else:
                i += 1
        if len(fields) < 2:
            continue
        try:
            pages.setdefault(block_id, int(fields[1]))
        except ValueError:
            # An unnumbered page style (roman front matter, say); not a
            # printout page, so nothing to compare.
            continue
    return pages


def discover_printouts(html_dir: Path) -> dict[str, str]:
    """Map printout id -> the HTML file whose print-preview link offers it."""
    found: dict[str, str] = {}
    for html_file in sorted(html_dir.rglob("*.html")):
        try:
            text = html_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for match in re.finditer(r'href="\?printpreview=([^"]+)"', text):
            found.setdefault(match.group(1), html_file.relative_to(html_dir).as_posix())
    return found


# -------------------------------------------------------------- HTML pages --


class _QuietHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args: Any) -> None:  # noqa: D102
        pass


def serve(directory: Path) -> tuple[socketserver.TCPServer, int]:
    handler = functools.partial(_QuietHandler, directory=str(directory))
    httpd = socketserver.TCPServer(("127.0.0.1", 0), handler)
    port = httpd.server_address[1]
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    return httpd, port


# Which .onepage each element with an id landed in, one-based.  An id nested
# inside a block reports the block's page, which is what we want: the join
# below only keeps ids LaTeX also labelled.
_PAGE_MAP_JS = """() => {
    const pages = [...document.querySelectorAll('section.onepage')];
    const map = {};
    pages.forEach((page, index) => {
        page.querySelectorAll('[id]').forEach(element => {
            if (!(element.id in map)) { map[element.id] = index + 1; }
        });
    });
    return {pageCount: pages.length, blocks: map};
}"""

_SIGNATURE_JS = """() => [...document.querySelectorAll('section.onepage')]
    .map(page => Math.round(page.getBoundingClientRect().height)).join(',')"""


# The preview starts with answers and solutions hidden and hints shown, and
# remembers the reader's choice in localStorage.  LaTeX has no such control:
# it prints whatever the publication file says it should, and every one of
# those settings defaults to showing the component.  Comparing the two in
# their default states therefore compares two different documents -- the PDF
# of a worksheet with worked solutions against the preview of the same
# worksheet without them -- which no amount of page-break machinery could
# reconcile.  So the preview is told to reveal everything, which is the state
# that matches a default LaTeX build.
_REVEAL_JS = """try {
    localStorage.setItem('hide-hint', 'false');
    localStorage.setItem('hide-answer', 'false');
    localStorage.setItem('hide-solution', 'false');
} catch (e) {}"""


def _settle(page: Any, stable_ticks: int = 5, interval_ms: int = 200, max_ticks: int = 100) -> bool:
    """Wait until the page heights stop changing; True if they did."""
    previous, stable = None, 0
    for _ in range(max_ticks):
        signature = page.evaluate(_SIGNATURE_JS)
        if signature == previous:
            stable += 1
            if stable >= stable_ticks:
                return True
        else:
            stable, previous = 0, signature
        page.wait_for_timeout(interval_ms)
    return False


def html_pages(
    base_url: str, printouts: dict[str, str], only: str | None, reveal: bool = True
) -> dict[str, dict]:
    """Drive the print preview in a browser; return per-printout page maps."""
    from playwright.sync_api import sync_playwright

    results: dict[str, dict] = {}
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        context = browser.new_context(viewport={"width": 1400, "height": 1000})
        if reveal:
            context.add_init_script(_REVEAL_JS)
        page = context.new_page()
        for printout_id, html_file in printouts.items():
            if only and printout_id != only:
                continue
            url = f"{base_url}/{html_file}?printpreview={printout_id}"
            print(f"[parity] preview {printout_id} ...", flush=True)
            page.goto(url, wait_until="networkidle", timeout=60000)
            # A web font landing late reflows every row and repaginates the
            # whole printout, so a measurement taken before the fonts are in
            # is a measurement of a different document.
            page.evaluate("() => document.fonts.ready")
            try:
                page.wait_for_selector("section.onepage", timeout=30000)
            except Exception:
                print(f"[parity]   no pages produced for {printout_id}; skipping")
                continue
            # Mirror pollUntilSettled(): stop once the page heights have not
            # changed for several ticks running, rather than after a fixed
            # wait.  Held to a longer window and a stricter run of stable
            # ticks than the page itself uses, because the page's own
            # pollUntilSettled() gives up after two seconds -- anything that
            # arrives later (a slow equation, an image finishing) repaginates
            # once more with nothing watching, and a reading taken in between
            # is not reproducible.  Read it twice and only trust a reading
            # that comes back the same both times.
            settled = _settle(page)
            first = page.evaluate(_PAGE_MAP_JS)
            page.wait_for_timeout(600)
            _settle(page)
            second = page.evaluate(_PAGE_MAP_JS)
            if first != second:
                print(f"[parity]   {printout_id} not settled; re-reading")
                page.wait_for_timeout(1500)
                _settle(page)
                third = page.evaluate(_PAGE_MAP_JS)
                settled = third == second
                second = third
            second["settled"] = bool(settled)
            results[printout_id] = second
        browser.close()
    return results


# ----------------------------------------------------------------- compare --


def compare(html_result: dict[str, dict], pdf_pages: dict[str, int]) -> dict:
    """Per printout, compare the HTML page of each block with the PDF page."""
    report: dict[str, Any] = {"printouts": {}, "totals": {}}
    total_blocks = total_matched = total_moved = 0
    for printout_id, data in sorted(html_result.items()):
        blocks = data["blocks"]
        shared = {b: page for b, page in blocks.items() if b in pdf_pages}
        if not shared:
            report["printouts"][printout_id] = {
                "html_pages": data["pageCount"],
                "blocks": 0,
                "note": "no blocks labelled in the PDF",
            }
            continue
        # PDF pages are absolute; the printout starts on the first one used.
        first_pdf_page = min(pdf_pages[b] for b in shared)
        rows = []
        moved = 0
        for block_id, html_page in sorted(shared.items(), key=lambda kv: kv[1]):
            pdf_page = pdf_pages[block_id] - first_pdf_page + 1
            if pdf_page != html_page:
                moved += 1
            rows.append({"id": block_id, "html": html_page, "pdf": pdf_page})
        pdf_page_span = max(pdf_pages[b] for b in shared) - first_pdf_page + 1
        report["printouts"][printout_id] = {
            "html_pages": data["pageCount"],
            "pdf_pages": pdf_page_span,
            "blocks": len(shared),
            "moved": moved,
            "settled": data.get("settled", True),
            "rows": rows,
        }
        total_blocks += len(shared)
        total_matched += len(shared) - moved
        total_moved += moved
    report["totals"] = {
        "blocks": total_blocks,
        "agree": total_matched,
        "moved": total_moved,
        "agreement": round(total_matched / total_blocks, 4) if total_blocks else None,
    }
    return report


def print_report(report: dict, baseline: dict | None) -> None:
    print()
    print("=" * 78)
    print("printout pagination parity: HTML print preview vs PDF")
    print("=" * 78)
    base_printouts = (baseline or {}).get("printouts", {})
    for printout_id, data in report["printouts"].items():
        if "note" in data:
            print(f"\n{printout_id}: {data['note']}")
            continue
        was = base_printouts.get(printout_id, {})
        delta = ""
        if "moved" in was:
            change = data["moved"] - was["moved"]
            if change:
                delta = f"  ({change:+d} vs baseline)"
            else:
                delta = "  (unchanged)"
        unsettled = "" if data.get("settled", True) else "  !unsettled"
        print(
            f"\n{printout_id}: {data['blocks']} blocks, "
            f"{data['moved']} on a different page"
            f"{delta}   [HTML {data['html_pages']}pp / PDF {data['pdf_pages']}pp]"
            f"{unsettled}"
        )
        for row in data["rows"]:
            if row["html"] != row["pdf"]:
                print(f"    {row['id']}: HTML page {row['html']}, PDF page {row['pdf']}")
    totals = report["totals"]
    print()
    print("-" * 78)
    if totals["blocks"]:
        print(
            f"TOTAL: {totals['agree']}/{totals['blocks']} blocks agree "
            f"({totals['agreement']:.1%}); {totals['moved']} disagree"
        )
        if baseline:
            base_totals = baseline["totals"]
            print(
                f"BASELINE: {base_totals['agree']}/{base_totals['blocks']} agreed "
                f"({base_totals['agreement']:.1%}); {base_totals['moved']} disagreed"
            )
    else:
        print("TOTAL: no blocks compared")
    print("-" * 78)


# -------------------------------------------------------------------- main --


def run_pair(
    project_root: Path,
    tex_target: str,
    html_target: str,
    only: str | None,
    generate: bool = False,
    reveal: bool = True,
) -> dict:
    tex_dir = build_target(
        project_root, tex_target, {"debug.printout.labels": "yes"}, generate=generate
    )
    aux_path = compile_pdf(tex_dir)
    pdf_pages = parse_aux(aux_path)
    print(f"[parity] {len(pdf_pages)} labelled blocks in {aux_path.name}")

    html_dir = build_target(project_root, html_target, {}, generate=generate)
    printouts = discover_printouts(html_dir)
    print(f"[parity] {len(printouts)} printouts in {html_target}")

    httpd, port = serve(html_dir)
    try:
        html_result = html_pages(f"http://127.0.0.1:{port}", printouts, only, reveal)
    finally:
        httpd.shutdown()
    return {"pdf_pages": pdf_pages, "html": html_result}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=Path("."), help="project root")
    parser.add_argument("--tex-target", default="sa-tex")
    parser.add_argument("--html-target", default="sa-web")
    parser.add_argument("--printout", default=None, help="restrict to one printout id")
    parser.add_argument("--save-baseline", action="store_true")
    parser.add_argument(
        "--generate", action="store_true", help="regenerate assets before building"
    )
    parser.add_argument(
        "--hide-solutions",
        action="store_true",
        help="leave the preview at its default visibility instead of revealing"
        " hints, answers and solutions to match a default LaTeX build",
    )
    parser.add_argument(
        "--reanalyze",
        action="store_true",
        help="recompute the comparison from the last run's saved measurements",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        default=None,
        help=f"baseline file (default: test-output/<tex-target>-{BASELINE_NAME})",
    )
    args = parser.parse_args()

    project_root = args.project.resolve()
    baseline_path = args.baseline or (
        project_root / "test-output" / f"{args.tex_target}-{BASELINE_NAME}"
    )

    raw_path = baseline_path.with_name(
        baseline_path.name.replace("-baseline.json", "-raw.json")
    )
    if args.reanalyze:
        raw = json.loads(raw_path.read_text(encoding="utf-8"))
    else:
        raw = run_pair(
            project_root,
            args.tex_target,
            args.html_target,
            args.printout,
            args.generate,
            not args.hide_solutions,
        )
        raw_path.parent.mkdir(parents=True, exist_ok=True)
        raw_path.write_text(json.dumps(raw, indent=2), encoding="utf-8")
    report = compare(raw["html"], raw["pdf_pages"])

    baseline = None
    if baseline_path.exists() and not args.save_baseline:
        baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    print_report(report, baseline)

    latest_path = baseline_path.with_name(baseline_path.name.replace("-baseline", "-latest"))
    latest_path.parent.mkdir(parents=True, exist_ok=True)
    latest_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\nwrote {latest_path}")
    if args.save_baseline:
        baseline_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"wrote {baseline_path}")


if __name__ == "__main__":
    sys.exit(main())
